post_install() {
    EXTRAMODULES='extramodules-5.8'
    depmod -a $(cat /lib/modules/$EXTRAMODULES/version)
    echo 'In order to use the rtl8192 module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-5.8'
    depmod -a $(cat /lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-5.8'
    depmod -a $(cat /lib/modules/$EXTRAMODULES/version)
    
}
