post_install() {
  echo "sna, uxa and glamor acceleration methods are supported"
  echo "With glamor set as sna"
  echo "Use either glamor or uxa method if you run into trouble with sna."
  echo "Try by creating /etc/X11/xorg.conf.d/20-intel.conf "
  echo "Section "Device" "
  echo "       Identifier  "Intel Graphics" "
  echo "       Driver      "intel" "
  echo "       Option      "AccelMethod"  "glamor" "
  echo "EndSection "
}

post_upgrade() {
  post_install
}
  