post_install() {
  echo "sna, uxa and now glamor too, acceleration methods are supported"
  echo "With sna set as default"
  echo "Use the uxa method if you run into trouble with sna."
  echo "Or try the all new glamor method, by creating /etc/X11/xorg.conf.d/20-intel.conf "
  echo "Section "Device" "
  echo "       Identifier  "Intel Graphics" "
  echo "       Driver      "intel" "
  echo "       Option      "AccelMethod"  "glamor" "
  echo "EndSection "
}

post_upgrade() {
  post_install
}
  