infodir=/usr/share/info
filelist=(annotate.info gdb.info gdb.info-1 gdb.info-2 gdb.info-3 gdb.info-4 gdb.info-5 gdb.info-6 stabs.info)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}
