post_install() {
  xdg-icon-resource forceupdate --theme hicolor 2> /dev/null
  if [ ! -f /etc/ssl/certs/java/cacerts ]; then
    /usr/sbin/init-jks-keystore
  fi
  echo "When you use a non-reparenting window manager"
  echo "set _JAVA_AWT_WM_NONREPARENTING=1 in the relevant"
  echo "/etc/profile.d/openjdk7.* file."
}

post_upgrade() {
  post_install
}


post_remove() {
  xdg-icon-resource forceupdate --theme hicolor 2> /dev/null
}
