post_install() {
    EXTRAMODULES='extramodules-6.7'
    depmod -a $(cat /lib/modules/$EXTRAMODULES/version)
    echo 'In order to use the rtl88x2bu module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-6.7'
    depmod -a $(cat /lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-6.7'
    depmod -a $(cat /lib/modules/$EXTRAMODULES/version)
    
}
