#!/bin/bash

if [ -e "/etc/rc.d/ntpdate" ]; then
	case "$2" in
		up)
			/etc/rc.d/ntpdate start
		;;
		vpn-up)
			/etc/rc.d/ntpdate start
		;;
		down)
			/etc/rc.d/ntpdate stop
		;;
		vpn-down)
			/etc/rc.d/ntpdate stop
		;;
	esac
fi

