
whisperer(){
    echo "----------------------------------------------------------------"
    echo "PLEASE NOTE:"
    echo "----------------------------------------------------------------"
    echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
    echo "--------------------- ^^^^^^^^^ --------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/grub.cfg , ie.:"
    echo "kernel /boot/vmlinuz-linux root=/dev/sda1 ro nomodeset"
    echo "----------------------------------------------------------------"
    echo "For more info and troubleshooting visit:"
    echo "http://chakra-linux.org/wiki/index.php/Switching_Between_Free_and_Non-free_Video-Drivers"
    echo "----------------------------------------------------------------"
}

check_libdri_so(){
    if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
        ln -sf usr/lib/xorg/modules/extensions/libdri.xorg usr/lib/xorg/modules/extensions/libdri.so
    fi
}


post_install(){
    check_libdri_so
    whisperer
}

post_upgrade(){
    check_libdri_so
    whisperer
}

post_remove(){
    # If the symlink is dead, remove it
     check_libdri_so
     echo "NOTE: Don't forget to recover your original xorg.conf file."
}
