#!/bin/bash


if [ -e /sys/fs/cgroup/systemd ]; then
        case "$2" in
                up)
                              systemctl start ntpd.service
                ;;
                down)
                              systemctl stop ntpd.service
                ;;
        esac
fi

