#!/bin/bash

timedate1() {
    gdbus call \
        --system \
        --object-path /org/freedesktop/timedate1 \
        --dest org.freedesktop.timedate1 \
        --method org.freedesktop.timedate1.SetNTP "$@"
}

if [ -e /sys/fs/cgroup/systemd ]; then
        case "$2" in
                up)
                        timedate1 true false
                ;;
                down)
                        timedate1 false false
                ;;
        esac
fi