
post_install() {
	cat <<EOT
----------------------------------------------------------------------------
> Configuration:  /etc/conf.d/splash
>     WIKI page:  http://wiki.archlinux.org/index.php/Fbsplash
----------------------------------------------------------------------------
EOT
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
	if [[ $( vercmp $2 1.2.7 ) -lt 0 ]]; then
		post_install
	fi
}

# EOF
